version: '3.8'

services:
  web1:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    env_file:
      - ./.env.prod
#    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    command: gunicorn -c ./gunicorn.ini hello_django.wsgi
    depends_on:
      - db
  web2:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    env_file:
      - ./.env.prod
    command: gunicorn -c ./gunicorn.ini hello_django.wsgi
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web1
      - web2

volumes:
  postgres_data:
